# Generated by Django 6.0.7 on 2026-09-08 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('verification', '0003_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='VALID', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='verification.verificationapplication')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='instruments.instrument')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
