# Generated by Django 6.1.1 on 2026-09-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_alter_verificationapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationapplication',
            name='application_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Verification'), ('RE_VERIFICATION', 'Re-verification'), ('RENEWAL', 'Renewal')], default='INITIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationapplication',
            name='previous_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_applications', to='verification.verificationapplication'),
        ),
    ]
