# Generated by Django 6.1.1 on 2026-09-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_instrument_instrument_uid'),
        ('verification', '0006_verificationapplication_application_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INSTRUMENT_PHOTO', 'Instrument Photo'), ('VERIFICATION_DOCUMENT', 'Verification Document'), ('INSPECTION_PHOTO', 'Inspection Photo'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='verification_documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.verificationapplication')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='instruments.instrument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
