# Generated by Django 6.1.1 on 2026-09-09 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrument_instrument_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_uid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
